config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  # contorollerにフォームデータを送信するのでpost
 
  post 'todolists' => 'todolists#create'
  # new画面で新規投稿された時にpostされこのcontorollerへ処理がつながる
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as:'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist' 
  # 新規投稿のHTTPメソッドは、POSTを使用、一方、更新の場合はPATCHで指定
  delete 'todolists/:id' => 'todolists#destroy',as:'destory_todolist'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  attachment:image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  
  def new
    # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
   @list = List.new
  end
  
  def create
    # １. データを新規登録するためのインスタンス作成　# listDBから取ってきた新規の情報をlistに代入
    list = List.new(list_params)
    # ２. データをデータベースに保存するためのsaveメソッド実行
    list.save
    # ３. トップ画面へリダイレクト
    redirect_to todolist_path(list.id)
    # <!--todolist_pathと表示できるのは、routesでget 'todolists/:id' => 'todolists#show', as:'todolist'と設定しているから????-->
    # _pathの使い方がイマイチわからない...
  end

  def index
    @lists = List.all 
    # すべてのデータが取り出されて格納されるため、インスタンス変数名を複数形にしている　1つのデータでいい場合は@listをインスタンスに使用する
  end

  def show
    @list = List.find(params[:id])
    # レコード1件を取得するので、インスタンス変数名は単数形の「@list」
    # params[:id]でrouteで受け取ったidを取れる 
  end
  
  def edit
    @list = List.find(params[:id])
  end
  
  def update
    list = List.find(params[:id])
    list.update(list_params)
    # この文はどういう意味？list変数に入った情報のupdateコラムを引き出す？list_paramsはどいいう意味？
    redirect_to todolist_path(list.id)
  end
  
  def destroy
    list = List.find(params[:id])  # データ（レコード）を1件取得
    list.destroy  # データ（レコード）を削除
    redirect_to todolists_path  # 投稿一覧画面へリダイレクト
    # 投稿一覧index(todolists_path:getの場合なので)
  end
  
  # privateより後に定義されたメソッドは、アクションとして認識されなくなる
  # privateメソッドの名前は、「モデル名_params」とすることが多い
  private
  def list_params
    params.require(:list).permit(:title,:body,:image)
    # 公式で確認
    # list（キー）モデルに対して、title,body,imageコラムを抽出したい
    # permitメソッドを使用する事で、許可された値のみを取得することができる
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "TodoLists", todolists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", todolists_new_path %>
        </li>
      </ul>
    </nav>
    <main>
    <%= yield %>
    </main>
    
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@list, url:"/todolists/#{@list.id}", local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>
<!--この画面の仕組みがまだわからない form_withの仕組み f.とtext_areaと:titleの関係は？？-->

app/views/todolists/index.html.erb
<div class="list-wrap">
<% @lists.each do |list| %>
  <div class="list-box">
    <%= attachment_image_tag list, :image, :fill, 200, 200, format: 'jpeg' %>
    <!--list = 表示する画像の入ったレコード、image = 画像のカラム名、-->
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
      <span class="list-title"><%=link_to list.title, todolist_path(list.id) %></span>
      <!--todolist_pathと表示できるのは、routesでget 'todolists/:id' => 'todolists#show', as:'todolist'と設定しているから-->
    </div>
  </div>
<% end %>
</div>

app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model: @list, url:'/todolists', local:true do |f| %>
<!--formタグでフォームをデータ送信　＠モデル名, 送るurl:, local:true do |変数を入れる？？|-->
<!--@listに入れた空データをfに入れている、任意の値-->
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <!--image_idカラムの_idを抜いたもの-->
  <%= f.submit '投稿' %>
  <!--「投稿する」ボタンを押すと、POSTメソッドの'/todolists'に送信-->
<% end %>

app/views/todolists/show.html.erb
<!--詳細画面-->
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list, :image, :fill, 100, 100, format: 'jpeg' %>
<!--attachment_image_tag 表示する画像の入ったレコード, :画像のカラム名-->
<!--image_idとつけたが、imageなのは何故か？？-->
<%= link_to"編集",edit_todolist_path(@list.id) %>
<!--get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'で定義しているのでedit_todolistのパスが使える？？？-->
<%= link_to "削除",destory_todolist_path(@list.id), method: :delete, "data-column" => "本当に削除しますか?"%>
<!--引数はmethod: :deleteを指定する-->